version: '3'

services:
  symfony:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: PHP
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    container_name: DB
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: portfolio
      MYSQL_PASSWORD: tf-rK4a3
      MYSQL_USER: Zozo921506