services:
  # PHP service
  - type: web
    name: symfony-php
    env: docker
    build:
      dockerfilePath: Dockerfile
      context: .
    ports:
      - 80
    envVars:
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}
    volumes:
      - /var/www/html/vendor
      - ./var:/var/www/html/var
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    # Note: Render does not directly support 'depends_on'. We handle dependencies with environment variables or manual setup

  # MySQL service (external managed service)
  - type: database
    name: symfony-db
    env: mysql
    plan: free  # Can be changed to a higher tier if needed
    dbVersion: "8.0"
    envVars:
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}
      - key: MYSQL_USER
        value: ${MYSQL_USER}
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}

volumes:
  - db_data:/var/lib/mysql  # Volumes are automatically managed by Render's database service
