services:
  - name: symfony-backend
    type: web
    env: docker
    plan: free
    dockerfilePath: .docker/php/Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: symfony-db
          property: connectionString

  - name: symfony-nginx
    type: web
    env: docker
    plan: free
    dockerfilePath: .docker/nginx/Dockerfile
    envVars:
      - key: BACKEND_URL
        value: http://symfony-backend:9000

  - name: symfony-db
    type: postgres
    plan: free
    databaseName: symfony
    user: symfony
